#!/usr/bin/python

import smbus
import time

#bus = smbus.SMBus(1) # Rev 2 Pi uses 1

DEVICE = 0x20 # Device address (A0-A2)
IODIRA = 0x00 # Pin direction register
OLATA  = 0x14 # Register for outputs
OLATB  = 0x15
GPIOA  = 0x12 # Register for inputs
GPIOB  = 0x13

empty_array = [ 0,0,0,0 ]
test_array = [ 3,1,0,0 ]

def run_motors(selection):
    # Main pour
    while selection != empty_array:
        for x in range (0, 4):
            print "Loop %s" % x
            if selection[x] > 0:
                print "Pour"
                selection[x] -= 1
    print selection
    return "Ok"



run_motors(test_array)



